version: '3.8'

services:
  web:
    build: .
    container_name: librekb_web
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} # set these values in .env file
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Mount the config.php so you can easily update settings without rebuilding the image.
      - ./config.php:/var/www/html/config.php

  db:
    image: mysql:8.1
    container_name: librekb_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # set these values in .env file
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - librekb_db_data:/var/lib/mysql

volumes:
  librekb_db_data:
    name: librekb_db_data
